var meals = [
    "Good bread, raw milk butter, pape clément vin de bordeaux",
    "Skirt steak with bearnaise and pomme frites, Beaujolais, fromage du chevre, Cote de Rhone",
    "Clambake over fire, Riesling, pork chops, Domaine Leroy burgundy ",
    "Margaritas, tagliatelle with tomato sauce, Chianti classico ",
    "Rice and beans with sofrito, corn tortillas, Pacifico ballenas ",
    "Pickled chanterelles and fiddleheads, venison rillettes. ",
    "Sloppy Joe, salad bar, bug juice, chocolate cookies",
    "2 conch fritters, 9 bottles of beer",
    "Roast beef, Yorkshire pudding, butter roasted carrots, Chateauneuf-du-Pape",
    "Raw oysters, grilled porcini with lemon salt, cod a la plancha with butter ",
    "Caviar, foie gras marshmallows, jamón ibérico, sparkling water",
    "Mac and cheese and hot dogs, cottage cheese, and canned clementines",
    "Dill pickles and ten black olives",
    "Peaches in syrup, shrimp, eels, pickled herring, tuna boiled in saltwater",
    "Red chile enchiladas with cheese and beans, sparkling water, one bottle of mid-range tequila, some limes, incredible--absolutely lights out--flan",
    "Chanterelle Farrotto, Canard Roti aux Olives, Salad de Radicchio a l'Orange, Trois Fromages, Deux Diables Brun, Croque en Bouche, Mes Amis sans eux je n'ai rien",
    "Lychees, clementines, olives, almonds, feta cheese",
    "Foot long hot dog, 12 oz Coke.",
    "Lemon ice in a plastic cup, wood spoon. ",
    "Pizzas, antipasti, summer squash soup, Dinah's Cheese, hard rolls, raw butter, pork loin and sage butter Yukon gold potatoes, milkshakes, sparkling wine, red wine ",
    "Baked John Dory with fennel, smoked oysters, dry pear cider",
    "64 oz frozen Coke, 1 liter of Vitamin Water",
    "Agedashi tofu, tonkatsu ramen, nigori sake ",
    "Wood-fired pizza, burrata, basil juleps. ",
    "Lou Malnati's minestrone soup, Pepsi",
    "Spicy tuna rolls, California rolls, miso soup, ebi maki",
    "Spoiled/buried/fried tuna, uni, live abalone, butterfish liver ",
    "Raw oysters, grilled bread with parsley sauce, boudin blanc, Mirror Pond pale ale",
    "Bacon cheeseburger, experimental chipotle ketchup made from dried peppers and a can of tomato sauce, homemade mezcal ",
    "Tortellini in veal stock, beefsteak tomatoes with salt, red wine",
    "Steamed clams with basil, onion, and beer, sourdough baguette  ",
    "Grilled langoustines, cioppino, seafood frittata, cheap bottle of sparkling wine ",
    "Fire roasted lamb, various seafood preparations, rice cakes, blood sausages",
    "Classic dinner breakfast of eggs over easy, three slices of bacon, shredded hash browns with ketchup, awful coffee ",
    "Pad thai, tofu spring rolls, tom yum soup ",
    "Whole steamed snapper, jasmine rice, beer ",
    "Challah, beet salad with pumping seeds, cavatappi with brown butter sauce",
    "Tuna six ways, red cabbage and cherry salad, ice cream sundaes",
    "Spaghetti",
    "Bread, salami, coppa, mortadella, gruyere, smoked bleu cheese, various lagers",
    "Roasted lamb shoulder with cumin and star anise, mashed rutabagas, iceberg salad with red cabbage accents and parsley vinaigrette ",
    "Bo Ssam, fried chicken, kim chi rolls",
    "Spit roasted whole pig, spit roasted goat, rabbit saddle and liver banh mi, buried whole pig, grilled oysters, rabbit Andouille sausage, roasted peppers",
    "Seared scallops, minted and mashed English peas, lardons, soave ",
    "Grilled bread, sautéed sardines, braised and quick friend suckling pig, olives, duck prosciutto, Irouleguy ",
    "Flat iron steaks, roasted carrots and sweet potatoes, kale salad with lemon juice ",
    "Hanger steak, day boat scallops, watermelon, octopus rolls with uni cream cheese, Manhattans, ice wine ",
    "Prawn sashimi with sriracha ice, bouillabaisse",
    "Venison stew, slivovitz ",
    "Exploding olives, gold leaf bread, omelette, patatas bravas, charcuterie, various cakes, txakoli",
    "Grilled beef rib eye, homemade potato chips, grilled sockeye salmon, beet salad with raisins and verjus, smoked sturgeon ",
    "Mozzarella sticks, bar tacos, pitchers of a now-unknown IPA ",
    "Schnitzel, borscht, Russian beer ",
    "Seared tuna with spinach, salt roasted potatoes, sparkling wine, bourbon ",
    "Roman lobster plate, jubilee four plate, crab legs in egg yolk, broiled black caviar, asparagus salmon roll, stewed goose, valedictorian shark fin goblet, wing lip original abalone, king oyster mushroom lamb steak, mushroom stewed silkie, hairy crab steamed rice cake, roasted scallop with chupei in seafood sauce, skillful handed char siu pastry, osmanthis flowers with red bean and coconut paste, jujube with lotus seeds, oasis fruit juice",
    "Kale salad with carrots and sunflower seeds, flax crackers with fromage blanc, salami, snicker doodles, and gruner veltliner  ",
    "Cincinnati-style chili, sweet tea",
    "Denver omelettes, hash browns, tabasco ",
    "Ham and cheese omelette, fried potatoes, sausage patties, vanilla milkshakes ",
    "Frisee salad with mussels and red wine, lamb shank with chimichurri",
    "Tonkatsu ramen, extra broth, extra noodles",
    "Chalupas and hard shell tacos for dinner, frappucinos",
    "Mushroom pastry tart, croque monsieur, gravlax with red onion creme fraiche and capers, mille feuille",
    "String cheese, warm vinho verde, crackers, half a banana ",
    "Shrimp salad roll with hoisin sauce ",
    "Baked brie with hazelnuts, radicchio salad with pepitas and white wine vinaigrette, seared steelhead with horseradish butter",
    "Roasted chicken breast, sautéed carrots, green leaf salad, red table wine ",
    "Alheira with goat cheese and chutney, clams with linguica and beer, snails in herb broth, thin pork sandwiches, gambas a Mozambique ",
    "Deer jerky, peanut butter energy bars ",
    "Blue cornmeal calamari, queso fundido, carne asada quesadillas, margaritas ",
    "Salt roasted whole branzino with chanterelles and pine nuts, butter lettuce and tarragon salad, Canary Islands white wine ",
    "Fried potatoes with lime and cojita, french press coffee ",
    "Takeout of smoked beef brisket, green chile macaroni and cheese, and iceberg wedge salad with blue cheese dressing and bacon ",
    "Fried eggs, biscuits and butter, instant coffee ",
    "Ham, popcorn, serendipitously discovered 30-year old rye whiskey ",
    "The Last Word; asparagus, osetra caviar, lemon, and pine nut crumble; various sashimi, blood orange; grilled Maine lobster, blood orange; squab breast potato-dandelion purée; champagne granité kumquat marmalade, honey, thyme; and candies to go ",
    "Wood-fired pepperoni pizza, chicken korma, noodle bowl with pork and shrimp, bacon cheeseburger with french fries, one bottle Dubel, one bottle La Fin du Monde ",
    "Grilled bratwurst, potato salad, Heineken",
    "Drip coffee, warm baguettes with mirabelle plum preserves, hard-boiled eggs, smoked bacon",
    "Meatball sandwiches with provolone and pickled peppers, two silver bullets",
    "Parker house rolls with tabasco, charcuterie with whole grain mustard, jazz apples ",
    "Chicken confit with a Brussels sprout and Kennebec potato hash ",
    "Ham, swiss, butter, & dijon mustard on ficelle",
    "Bangus and eggplant with shrimp paste, gulaman and sago with rum ",
    "Baked steel cuts oats with soy sauce, scallions, and shrimp paste ",
    "Baked brie with hazelnuts, radicchio salad with pepitas and white wine vinaigrette, seared steelhead with horseradish butter",
    "Fried cod, Dungeness crab cocktails, raw Depoe Bay oysters ",
    "Shoyu ramen, potstickers, oolong tea ",
    "Garlic soup with croutons, roast pork with dumplings and cabbage, Czechvar",
    "Green papaya salad with tofu, cardamom cookies ",
    "A selection of Avignon, Montelimar, Mille Feuille, and Poire Helene with fresh roasted cashews",
    "Brisket burrito with scrambled eggs, red chiles, and cheese, horchata ",
    "Roast beef and Roquefort sandwiches, chouquettes",
    "Peanut butter and honey on a demi-baguette, coffee with cream",
    "Bologna and cheese sandwiches, corn chips, red fruit punch",
    "Nachos, hot dogs, peanuts, and Pepsi",
    "Lobster rolls, one pear, and two bottles of white wine",
    "Pork braised in milk, sautéed bitter greens, foraged mushrooms and potato puree",
    "Clam chowder, cider braised chicken sandwich, beer ",
    "Seared weathervane scallops with Meyer lemon preserve and olives",
    "Snapper stuffed with crab cakes, rolled in pecans and then fried, red beans and rice ",
    "Trdelnik rolled pastries, beer ",
    "House smoked salmon, risotto, fried clams, brioche with raw butter and honey ",
    "Grilled cheese with mango chutney and sweet hot mustard, ghost pepper vodka, red table wines ",
    "Beef bulgogi, pa jun, kim chi, kimchichigae",
    "Crab with pine, mushroom, plantain; tagliatelle with huckleberries, black truffle, veal heart; sweetbreads with red eye gravy and house mustard; seared beef with ramps; smoked bleu cheese; madeleines; tequila, gin, gruner veltliner, Beaujolais ",
    "Shrimp Louie, lingcod with a garlic tomato shrimp butter sauce",
    "Trout and clam stew with fresh tomatoes and thyme ",
    "Fried anchovies, fresh tomatoes, white sheep's cheese, black olives, black tea, raki ",
    "French fries, bourbon ",
    "“Plate of Cakes”",
    "Wood-fired pizza with a solitary basil leaf in the center, Alicante Bouschet",
    "Monkfish in lemon sauce, cured ham, croissants with butter, chocolates",
    "Baked beans, hot dogs, cold fried chicken, iceberg lettuce salad, Genesee Cream Ale, instant coffee, RC Cola",
    "Dashi braised beef short ribs, duk bok ki, malbec",
    "Cold fried chicken, manchego, flax crackers, cashews, almonds, Pabst Blue Ribbon",
    "Pancakes with syrup and whipped cream, bacon",
    "Miso soup with clams, sashimi, tuna roll, vegetable tempure, sauvignon blanc ",
    "Lentil, paneer, and chickpea samosas; black chickpea and onion cakes in coconut curry; tamarind and yogurt chicken; meeti roti; Riesling",
    "Flank steak with french fries, baked pasta with bechamel, belle poire helene, sparkling wine",
    "Goat cheese and lavender fondue, plin with lemon oil and pork, spicy pork sausage",
    "Roasted whole sardines, gnocchi with fresh peas, mushrooms, grilled onions, lemon-thyme cream ",
    "Braised pork shank with cider and rosemary",
    "Fried artichoke hearts, sweet and sour rice, ginger carrot soup"
];
